import './global.css'
import { Roboto_Condensed } from 'next/font/google'

const roboto = Roboto_Condensed({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}